### PR TITLE
support in-repo-engines

### LINKED ISSUE #3: tests aren't showing meaningful content
screen shot 2017-10-10 at 10 14 28 am

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #3.

This now works in in-repo-engines. Not sure if I broke other app setups though, because this stuff is hard to test.

### CODE REVIEW

**Comment by kellyselden** [comment]
@dfreeman Do you want to test it in your apps to see if it didn't break it in non-engines?

**Comment by dfreeman** [comment]
Everything looks good in a couple projects that I tried linking this branch in.

If I merge this and do a release, will that unblock the work you're doing, or have you run into any other things we should get fixed first?

**Comment by kellyselden** [comment]
This is all I need. I'm using my fork with success.

**Comment by dfreeman** [comment]
Released v1.1.0. Thanks again!

**Comment by kellyselden** [comment]
Woohoo!

**Comment by kellyselden** [comment]
Thanks for these nice addons!

**Pull request merged**
